FROM nginx:latest

COPY . /usr/share/nginx/html
# docker build -t hosting-docker:latest .
# docker run -p 8085:80 hosting-docker:latest
# docker run -p 8085:80 -d --name "my_container" hosting-docker:latest